"""baseline schema (pre-fixes)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-08

IMPORTANT: There was no Alembic in this project before now - the schema
only ever existed via SQLAlchemy's Base.metadata.create_all(), which
creates missing tables but never alters existing ones. This migration is a
best-effort reconstruction of that original schema (as the model files
looked before any of the fixes in this session or the approval-workflow
session before it), written by hand rather than autogenerated against a
live database.

If you're adopting this on a database that was created by the old
create_all()-only setup: your tables should already match this shape, so
you do NOT need to actually run this one - instead run:

    alembic stamp 0001_baseline

which marks this revision as "already applied" without touching any
table, then run `alembic upgrade head` to apply 0002 (the real, new
schema changes) on top of your existing data.

Only run this migration for real (`alembic upgrade head` from empty) when
setting up a brand new, empty database - in which case create_all() at
app startup will actually create everything before Alembic ever runs, so
in practice this file mostly exists to give 0002 something to depend on
and to document the starting shape.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "Users",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("userid", sa.String(10), unique=True),
        sa.Column("name", sa.String(80)),
        sa.Column("company_mail", sa.String(50)),
        sa.Column("phone_number", sa.String(20)),
        sa.Column("isAlive", sa.Boolean, server_default=sa.true()),
    )

    op.create_table(
        "Passwords",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("Users.id"), primary_key=True),
        sa.Column("username", sa.String(10), unique=True),
        sa.Column("password", sa.String(60)),
    )

    op.create_table(
        "Roles",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("role", sa.Enum("admin", "manager", "employee", name="role_enum")),
    )

    op.create_table(
        "Role_Assignments",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("Users.id"), primary_key=True),
        sa.Column("role_id", sa.Integer, sa.ForeignKey("Roles.id"), primary_key=True),
    )

    op.create_table(
        "Manager_Assignments",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("Users.id"), primary_key=True),
        sa.Column("manager_id", sa.Integer, sa.ForeignKey("Users.id"), primary_key=True),
    )

    op.create_table(
        "Projects",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(50)),
        sa.Column("start_date", sa.Date),
        sa.Column("end_date", sa.Date),
        sa.Column(
            "status",
            sa.Enum("created", "in_progress", "completed", "archived", name="project_status_enum"),
        ),
    )

    op.create_table(
        "Project_Assignments",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("Users.id"), primary_key=True),
        sa.Column("project_id", sa.Integer, sa.ForeignKey("Projects.id"), primary_key=True),
    )

    op.create_table(
        "Tasks",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("project_id", sa.Integer, sa.ForeignKey("Projects.id")),
        sa.Column("name", sa.String(100)),
        sa.Column("description", sa.String(300)),
        sa.Column("isAlive", sa.Boolean, server_default=sa.true()),
    )

    op.create_table(
        "Time_Logs",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("Users.id")),
        sa.Column("project_id", sa.Integer, sa.ForeignKey("Projects.id")),
        sa.Column("task_id", sa.Integer, sa.ForeignKey("Tasks.id")),
        sa.Column("start_time", sa.TIMESTAMP),
        sa.Column("end_time", sa.TIMESTAMP),
        sa.Column("type", sa.Enum("standard", "overtime", name="log_type_enum")),
        sa.Column("comments", sa.String(300)),
    )


def downgrade() -> None:
    op.drop_table("Time_Logs")
    op.drop_table("Tasks")
    op.drop_table("Project_Assignments")
    op.drop_table("Projects")
    op.drop_table("Manager_Assignments")
    op.drop_table("Role_Assignments")
    op.drop_table("Roles")
    op.drop_table("Passwords")
    op.drop_table("Users")
